services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    environment:
      PORT: "4000"
      DATABASE_URL: ${DATABASE_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ACCESS_TOKEN_EXPIRES_IN: ${ACCESS_TOKEN_EXPIRES_IN}
      REFRESH_TOKEN_EXPIRES_IN: ${REFRESH_TOKEN_EXPIRES_IN}
      MAILTRAP_USER: ${MAILTRAP_USER}
      MAILTRAP_PASS: ${MAILTRAP_PASS}
      APP_URL: ${APP_URL}
      GROQ_API_KEY: ${GROQ_API_KEY}
      AI_API_URL: "http://ai:5000/predict"
    depends_on:
      - db
      - ai

  ai:
    build:
      context: ./AI
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"

volumes:
  postgres_data: